version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    target-branch: dev
    schedule:
      interval: weekly
      day: monday
      time: "04:00"
      timezone: Europe/Moscow
    open-pull-requests-limit: 5

  - package-ecosystem: npm
    directory: /
    target-branch: dev
    schedule:
      interval: weekly
      day: monday
      time: "04:30"
      timezone: Europe/Moscow
    open-pull-requests-limit: 5
    groups:
      root-minor-and-patch:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
